language: python
python:
  - "3.4"

script:
  - pip install -r requirements.txt
  - cd ./superlists
  - python manage.py test
  - python manage.py runserver &
  - sleep 5
  - python functional_tests.py