language: python
python:
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source=superlists manage.py test
  - cd ./superlists
  - python manage.py test

after_success:
  - coveralls