language: python
python:
  - "3.4"

install:
  - pip install -r requirements.txt
script:
  - cd ./superlists
  - python manage.py test --with-coverage --cover-package=lists

after_success:
  - coveralls

addons:
  firefox: "17.0"